create table public.items
(
    id               bigint generated by default as identity primary key,
    filename         varchar(255)  not null,
    size             integer not null,
    hash             integer not null,
    owner            varchar(255)  not null,
    data             bytea
);